import OpenAI from 'openai';

interface Plan {
  id: string;
  name: string;
  description: string;
  type: string;
  techStack: string[];
}

interface GeneratedFile {
  name: string;
  path: string;
  content: string;
  type: string;
}

class CodeGenerationService {
  private openai: OpenAI | null = null;

  constructor() {
    // Initialize OpenAI only if API key is available
    if (process.env.OPENAI_API_KEY) {
      this.openai = new OpenAI({
        apiKey: process.env.OPENAI_API_KEY
      });
    }
  }

  async generateProjectFiles(plan: Plan): Promise<GeneratedFile[]> {
    const files: GeneratedFile[] = [];

    try {
      // Use AI generation if available, otherwise use enhanced templates
      if (this.openai) {
        console.log('?? Using AI-powered generation');
        return await this.generateWithAI(plan);
      } else {
        console.log('? Using enhanced template generation');
        return await this.generateWithEnhancedTemplates(plan);
      }
    } catch (error) {
      console.error('? Generation error, falling back to templates:', error);
      return await this.generateWithEnhancedTemplates(plan);
    }
  }

  private async generateWithAI(plan: Plan): Promise<GeneratedFile[]> {
    const files: GeneratedFile[] = [];

    // Generate package.json with AI
    const packagePrompt = `Generate a complete package.json for a ${plan.type} project called "${plan.name}". 
    Description: ${plan.description}
    Tech stack: ${plan.techStack.join(', ')}
    Make it production-ready with proper dependencies, scripts, and metadata.`;

    const packageResponse = await this.openai!.chat.completions.create({
      model: 'gpt-4',
      messages: [{ role: 'user', content: packagePrompt }],
      temperature: 0.7
    });

    files.push({
      name: 'package.json',
      path: 'package.json',
      content: this.extractCodeFromResponse(packageResponse.choices[0].message.content || ''),
      type: 'json'
    });

    // Generate main application file with AI
    const appPrompt = `Create a complete, functional ${plan.techStack.includes('React') ? 'React' : 'JavaScript'} application for: ${plan.description}
    
    Requirements:
    - Project name: ${plan.name}
    - Type: ${plan.type}
    - Make it fully functional with realistic features
    - Include proper state management
    - Add interactive components
    - Use modern best practices
    
    Return only the code, no explanations.`;

    const appResponse = await this.openai!.chat.completions.create({
      model: 'gpt-4',
      messages: [{ role: 'user', content: appPrompt }],
      temperature: 0.8
    });

    files.push({
      name: plan.techStack.includes('React') ? 'App.tsx' : 'app.js',
      path: plan.techStack.includes('React') ? 'src/App.tsx' : 'app.js',
      content: this.extractCodeFromResponse(appResponse.choices[0].message.content || ''),
      type: plan.techStack.includes('React') ? 'tsx' : 'js'
    });

    // Generate HTML with AI
    const htmlPrompt = `Create a complete index.html file for "${plan.name}" - ${plan.description}
    Include proper meta tags, title, and structure for a ${plan.type} application.
    Make it professional and production-ready.`;

    const htmlResponse = await this.openai!.chat.completions.create({
      model: 'gpt-4',
      messages: [{ role: 'user', content: htmlPrompt }],
      temperature: 0.6
    });

    files.push({
      name: 'index.html',
      path: 'index.html',
      content: this.extractCodeFromResponse(htmlResponse.choices[0].message.content || ''),
      type: 'html'
    });

    return files;
  }

  private async generateWithEnhancedTemplates(plan: Plan): Promise<GeneratedFile[]> {
    const files: GeneratedFile[] = [];
    
    // Enhanced dynamic templates with variation
    const timestamp = Date.now();
    const randomFeatures = this.generateRandomFeatures(plan.type);
    
    // Dynamic package.json based on actual project requirements
    files.push({
      name: 'package.json',
      path: 'package.json',
      content: JSON.stringify({
        name: plan.name.toLowerCase().replace(/\s+/g, '-'),
        version: '1.0.0',
        description: `${plan.description} - Generated by CodePilot AI`,
        main: plan.techStack.includes('React') ? 'src/App.tsx' : 'app.js',
        scripts: {
          dev: plan.techStack.includes('Vite') ? 'vite' : 'node app.js',
          build: plan.techStack.includes('React') ? 'tsc && vite build' : 'echo "No build step"',
          preview: plan.techStack.includes('Vite') ? 'vite preview' : 'node app.js',
          test: 'echo "No tests yet"'
        },
        dependencies: this.getDynamicDependencies(plan),
        devDependencies: this.getDynamicDevDependencies(plan),
        keywords: this.generateKeywords(plan),
        author: 'CodePilot AI',
        license: 'MIT',
        repository: {
          type: 'git',
          url: `https://github.com/codepilot-ai/${plan.name.toLowerCase().replace(/\s+/g, '-')}`
        }
      }, null, 2),
      type: 'json'
    });

    // Dynamic application code with real functionality
    files.push({
      name: plan.techStack.includes('React') ? 'App.tsx' : 'app.js',
      path: plan.techStack.includes('React') ? 'src/App.tsx' : 'app.js',
      content: this.generateDynamicAppCode(plan, randomFeatures),
      type: plan.techStack.includes('React') ? 'tsx' : 'js'
    });

    // Enhanced HTML with dynamic content
    files.push({
      name: 'index.html',
      path: 'index.html',
      content: this.generateDynamicHTML(plan),
      type: 'html'
    });

    // Dynamic CSS with theme variations
    files.push({
      name: 'styles.css',
      path: 'styles.css',
      content: this.generateDynamicCSS(plan),
      type: 'css'
    });

    // Dynamic README with real project details
    files.push({
      name: 'README.md',
      path: 'README.md',
      content: this.generateDynamicREADME(plan, randomFeatures),
      type: 'md'
    });

    return files;
  }

  private extractCodeFromResponse(response: string): string {
    // Extract code from markdown code blocks
    const codeMatch = response.match(/``````/);
    return codeMatch ? codeMatch[1] : response;
  }

  private generateRandomFeatures(projectType: string): string[] {
    const features = {
      ecommerce: ['shopping cart', 'product search', 'user reviews', 'payment integration', 'inventory tracking'],
      blog: ['comment system', 'tag filtering', 'social sharing', 'RSS feed', 'author profiles'],
      dashboard: ['real-time charts', 'data export', 'user management', 'analytics widgets', 'notification system'],
      general: ['responsive design', 'dark mode', 'user authentication', 'API integration', 'progressive web app']
    };
    
    const availableFeatures = features[projectType] || features.general;
    return availableFeatures.sort(() => 0.5 - Math.random()).slice(0, 3);
  }

  private getDynamicDependencies(plan: Plan): Record<string, string> {
    const deps: Record<string, string> = {};
    
    if (plan.techStack.includes('React')) {
      deps.react = '^18.2.0';
      deps['react-dom'] = '^18.2.0';
    }
    
    if (plan.techStack.includes('TypeScript')) {
      deps.typescript = '^5.0.0';
      deps['@types/react'] = '^18.2.0';
      deps['@types/react-dom'] = '^18.2.0';
    }
    
    if (plan.techStack.includes('Stripe')) {
      deps['@stripe/stripe-js'] = '^2.1.0';
    }
    
    if (plan.type === 'ecommerce') {
      deps.axios = '^1.5.0';
      deps['react-router-dom'] = '^6.15.0';
    }
    
    return deps;
  }

  private getDynamicDevDependencies(plan: Plan): Record<string, string> {
    const devDeps: Record<string, string> = {};
    
    if (plan.techStack.includes('Vite')) {
      devDeps.vite = '^4.4.0';
      devDeps['@vitejs/plugin-react'] = '^4.0.0';
    }
    
    if (plan.techStack.includes('Tailwind CSS')) {
      devDeps.tailwindcss = '^3.3.0';
      devDeps.autoprefixer = '^10.4.0';
      devDeps.postcss = '^8.4.0';
    }
    
    return devDeps;
  }

  private generateKeywords(plan: Plan): string[] {
    const baseKeywords = ['codepilot', 'ai-generated', plan.type];
    const typeKeywords = {
      ecommerce: ['shopping', 'store', 'commerce', 'retail'],
      blog: ['content', 'writing', 'publishing', 'cms'],
      dashboard: ['analytics', 'monitoring', 'data', 'visualization']
    };
    
    return [...baseKeywords, ...(typeKeywords[plan.type] || [])];
  }

  private generateDynamicAppCode(plan: Plan, features: string[]): string {
    // This would generate much more dynamic code based on the plan
    // For now, enhanced template with variations
    const variations = [
      'gradient-to-br from-blue-500 to-purple-600',
      'gradient-to-tr from-green-400 to-blue-500',
      'gradient-to-bl from-pink-500 to-yellow-500'
    ];
    
    const selectedGradient = variations[Math.floor(Math.random() * variations.length)];
    
    return `// Generated by CodePilot AI - ${new Date().toISOString()}
import React, { useState, useEffect } from 'react';

// Dynamic features: ${features.join(', ')}
const features = ${JSON.stringify(features, null, 2)};

export default function App() {
  const [isLoaded, setIsLoaded] = useState(false);
  
  useEffect(() => {
    setIsLoaded(true);
  }, []);
  
  return (
    <div className="min-h-screen bg-${selectedGradient} flex items-center justify-center">
      <div className="text-center text-white p-8 rounded-lg backdrop-blur-sm bg-white/10">
        <h1 className="text-4xl font-bold mb-4">${plan.name}</h1>
        <p className="text-xl mb-6">${plan.description}</p>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-8">
          {features.map((feature, index) => (
            <div key={index} className="bg-white/20 p-4 rounded-lg">
              <h3 className="font-semibold capitalize">{feature}</h3>
              <p className="text-sm opacity-75">Coming soon</p>
            </div>
          ))}
        </div>
        
        <div className="mt-8 text-sm opacity-75">
          Generated by CodePilot AI • Project ID: ${plan.id}
        </div>
      </div>
    </div>
  );
}`;
  }

  private generateDynamicHTML(plan: Plan): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${plan.name} - ${plan.description}</title>
  <meta name="description" content="${plan.description} - Built with CodePilot AI">
  <meta name="keywords" content="${this.generateKeywords(plan).join(', ')}">
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>??</text></svg>">
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.tsx"></script>
  <!-- Generated by CodePilot AI on ${new Date().toISOString()} -->
</body>
</html>`;
  }

  private generateDynamicCSS(plan: Plan): string {
    const colorSchemes = [
      { primary: '#3B82F6', secondary: '#8B5CF6', accent: '#10B981' },
      { primary: '#EF4444', secondary: '#F59E0B', accent: '#8B5CF6' },
      { primary: '#10B981', secondary: '#3B82F6', accent: '#F59E0B' }
    ];
    
    const colors = colorSchemes[Math.floor(Math.random() * colorSchemes.length)];
    
    return `/* Generated by CodePilot AI for ${plan.name} */
/* Project Type: ${plan.type} */
/* Generated: ${new Date().toISOString()} */

:root {
  --primary-color: ${colors.primary};
  --secondary-color: ${colors.secondary};
  --accent-color: ${colors.accent};
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
  margin: 0;
  padding: 0;
  background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
}

.card {
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
  border-radius: 1rem;
  padding: 2rem;
  margin: 1rem 0;
  border: 1px solid rgba(255, 255, 255, 0.2);
}

/* Dynamic animations */
@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.fade-in {
  animation: fadeInUp 0.6s ease-out;
}

/* Responsive design */
@media (max-width: 768px) {
  .container {
    padding: 1rem;
  }
}`;
  }

  private generateDynamicREADME(plan: Plan, features: string[]): string {
    return `# ${plan.name}

${plan.description}

## ?? Generated by CodePilot AI

This project was automatically generated using CodePilot AI technology on ${new Date().toLocaleDateString()}.

## ?? Project Details

- **Type**: ${plan.type}
- **Tech Stack**: ${plan.techStack.join(', ')}
- **Project ID**: ${plan.id}

## ? Features

${features.map(feature => `- ${feature.charAt(0).toUpperCase() + feature.slice(1)}`).join('\n')}

## ??? Getting Started

### Prerequisites

- Node.js 18+ 
- npm or yarn

### Installation

\`\`\`bash
npm install
npm run dev
\`\`\`

### Build for Production

\`\`\`bash
npm run build
\`\`\`

## ?? Project Structure

\`\`\`
${plan.name.toLowerCase().replace(/\s+/g, '-')}/
+-- package.json
+-- index.html
+-- ${plan.techStack.includes('React') ? 'src/' : ''}
${plan.techStack.includes('React') ? '¦   +-- App.tsx' : '+-- app.js'}
+-- styles.css
+-- README.md
\`\`\`

## ?? Customization

This is a starter template. You can customize:

- Colors and themes in \`styles.css\`
- Components and functionality in the main app file
- Dependencies in \`package.json\`

## ?? About CodePilot AI

CodePilot AI is an intelligent development platform that transforms natural language descriptions into working applications.

---

*Generated on ${new Date().toISOString()} with ?? by CodePilot AI*
`;
  }
}

export const codeGenerationService = new CodeGenerationService();
